### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by johntom** [ciferblat/sails-firebirdsql#2]
Hi,
Thanks much for your contribution I'm testing now and looking forward to using.
John

**Comment by johntom** [comment]
Hi
Cant seem to connect and get data with waterline adapter. Any help appreciated. Will build a sample for the repo.
Thanks,
John


sails version 10,
nodejs 4.2.2
firebird 2.5.4
connections.js
  sailsFirebirdsql: {
        adapter : 'sails-firebirdsql',
        host: "127.0.0.1",
        port: 3050,
        user: 'SYSDBA',
        password: 'masterkey',
        database: 'c:\\firebird\\data\\mas\\mastest.gdb'
    },
Models/Claim.js

module.exports = {
  adapter: 'sailsFirebirdsql',
attributes: {
  }
};
api call
http://localhost:1337/api/claim
does not connect to database and fails on both dialect 1 and 3.


info: Starting app...

warn: `sails.config.express` is deprecated; use `sails.config.http` instead.
[Error: The specified procedure could not be found.
\\?\c:\sails10\brmAgenda\node_modules\agenda\node_modules\mongodb\node_modules\bson\build\Release\bson.node]
js-bson: Failed to load c++ bson extension, using pure JS version
[Error: The specified procedure could not be found.
\\?\c:\sails10\brmAgenda\node_modules\sails-mongo\node_modules\mongodb\node_modules\bson\build\Release\bson.node]
js-bson: Failed to load c++ bson extension, using pure JS version
database
connect deprecated res.headerSent: use standard res.headersSent node_modules\sails\node_modules\express\node_modules\connect\lib\proto.js:129:22
connect deprecated res.on("header"): use on-headers npm module instead node_modules\sails\node_modules\express\node_modules\connect\lib\middleware\session.js:247:9
find
err  Error (E_UNKNOWN) :: Encountered an unexpected error
: Dynamic SQL Error, SQL error code = -204, Table unknown, claim, At line 1, column 124
    at doCallback (c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\index.js:1234:18)
    at c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\index.js:2905:21
    at c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\messages.js:151:25
    at search (c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\messages.js:117:13)
    at c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

Details:  Error: Dynamic SQL Error, SQL error code = -204, Table unknown, claim, At line 1, column 124
 undefined
find
err  Error (E_UNKNOWN) :: Encountered an unexpected error
: Dynamic SQL Error, SQL error code = -204, Table unknown, claim, At line 1, column 124
    at doCallback (c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\index.js:1234:18)
    at c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\index.js:2905:21
    at c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\messages.js:151:25
    at search (c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\messages.js:117:13)
    at c:\sails10\brmAgenda\node_modules\sails-firebirdsql\node_modules\node-firebird\lib\messages.js:54:21
    at FSReqWrap.wrapper [as oncomplete] (fs.js:576:17)

Details:  Error: Dynamic SQL Error, SQL error code = -204, Table unknown, claim, At line 1, column 124
 undefined

**Comment by johntom** [comment]
Tests passed against same database

c:\sails10\brmAgenda\node_modules\sails-firebirdsql>npm test

> sails-firebirdsql@0.10.0 test c:\sails10\brmAgenda\node_modules\sails-firebirdsql
> node test/integration/runner -R spec -b

info: Testing `sails-firebirdsql`, a Sails adapter.
info: Running `waterline-adapter-tests` against 1 interfaces...
info: ( semantic )

debug: Latest draft of Waterline adapter interface spec:
debug: https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md



  Semantic Interface
    .create()
      √ should create a new record
      √ should return a generated PK
      √ should return generated timestamps
      √ should return a model instance
      √ should normalize undefined values to null
      √ should return rows in the correct order when creating multiple rows (173ms)
      overloaded usage of create
        √ should have saved the proper values (with auto-increment values)

  Semantic Interface
    .createEach()
      √ should create a set of users
      √ should insert 2 records verififed by find
      √ should return model instances

  Semantic Interface
    .destroy()
      a single record
        √ should destroy a record
        √ should return an empty array when searched for
      with numeric ID
        √ should destroy a record
        √ should return an empty array when searched for
      multiple records
        √ should destroy all the records
        √ should return an empty array when searched for
      IN query
        √ should not destroy any records

  Semantic Interface
    .find()
      √ should return 10 records
      √ should return 1 record when searching for a specific record (integer test) with find
      √ should parse multi-level criteria
      √ should return a model instance
      √ should work with no criteria passed in

  Semantic Interface
    .findOne()
      √ should return a single record
      √ should return a model instance
      √ should return null if a record is not found
      √ should work with just an id passed in

  Semantic Interface
    .findOrCreate()
      √ should create a new record
      √ should return a single record
      √ should only have a single record in the database
      √ should return a model instance
      √ should take search criteria as values
      √ should accept array of objects
      √ should return error if search criteria length does not match values

  Semantic Interface
    .findOrCreateEach()
      √ should create new user(s) for the one that doesn't exist
      √ should find a user that does exist
      √ should only have a single record for keys that exist
      √ should fail when only one arg is specified
      √ should return model instances

  Semantic Interface
    Array Type
      with valid data
        √ should store proper array value

  Semantic Interface
    Binary Type
      with valid data
        - should store proper binary value

  Semantic Interface
    Boolean Type
      with valid data
        √ should store proper boolean value

  Semantic Interface
    Date Type
      with valid data
        √ should store proper date value

  Semantic Interface
    Float Type
      with valid data
        √ should store proper float value

  Semantic Interface
    Integer Type
      with valid data
        √ should store proper integer

  Semantic Interface
    JSON Type
      with valid data
        √ should store proper object value

  Semantic Interface
    String Type
      with valid data
        √ should store proper string value

  Semantic Interface
    .update()
      attributes
        √ should update model attributes
        √ should return model instances
        √ should work with just an ID passed in
        √ should work with an empty object
        √ should work with null values
        √ should update model attributes without supplying required fields
      find updated records
        √ should allow the record to be found


  52 passing (2s)
  1 pending

time elapsed: 1902ms

**Comment by johntom** [comment]
I have it working when I create route with controller function. The default blueprint action displays the error (Details: Error: Dynamic SQL Error, SQL error code = -204, Table unknown, claim, At line 1, column 124
undefined
find
err Error (E_UNKNOWN) :: Encountered an unexpected error). Closing for now and will create sample asap.
Thanks,

module.exports = {
	  find: function (req, res) {
        console.log('find------------- ')
     Claim.query('Select ID,"ClaimNo","AdjusterID","Zip" from "Claim" where id < 200', function(error,results){
        function(error,results){
           
                 console.log('err ',error,results)
                if (error) {
                } else {
                    res.send(results);
                }
            });
    },
 _config: {}
};
